name: Scrape Spinny & Upload to Databricks

on:
  workflow_dispatch:  # or schedule: for auto-run

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests pandas databricks-cli

    - name: Run scraper
      run: python scraper.py

    - name: Configure Databricks CLI
      run: |
        databricks configure --token <<< "${{ secrets.DATABRICKS_HOST }}\n${{ secrets.DATABRICKS_TOKEN }}"

    - name: Upload CSV to Volume
      run: |
        databricks fs cp --overwrite spinny_temp_upload.csv dbfs:/Volumes/dev_blue/bronze/used_cars_ingestion/spinny_data.csv
